### ISSUE TITLE
AH64D  Missing Buttons

### ISSUE THREAD

**Issue by Petedcc** [DCS-Skunkworks/dcs-bios#1006]
### Version

- [X] I am using the latest version

### Aircraft

AH-64D

### Control

Stores Jettison and Emergency panels

### Description

All the lights work but the buttons listed dont have refs in bios, could these be added please?
Emergency Panel:
Hydraulics button

Stores Jettison: (Arm/Safe)
L Tip, L Outboard, L inboard, R Tip, R Outboard, R inboard,

**Comment by charliefoxtwo** [comment]
Are these not the store jettison buttons?
```
PLT_JETT_STORE_LO
PLT_JETT_STORE_LI
PLT_JETT_STORE_RI
PLT_JETT_STORE_RO
PLT_JETT_STORE_LW
PLT_JETT_STORE_RW
```

**Comment by charliefoxtwo** [comment]
Likewise, it looks like the emergency hydraulics button may be `PLT_EMERG_HYD_BTN`

These are all in the `PLT Left Console` category

**Comment by Petedcc** [comment]
> Are these not the store jettison buttons?
> 
> ```
> PLT_JETT_STORE_LO
> PLT_JETT_STORE_LI
> PLT_JETT_STORE_RI
> PLT_JETT_STORE_RO
> PLT_JETT_STORE_LW
> PLT_JETT_STORE_RW
> ```

I dont seem to have these, im using the nightly update version?
And yes im just blind with the hydraulics, thankyou!

**Comment by charliefoxtwo** [comment]
The jettison store buttons were added back when the module was first added as far as I know. I just checked, and they're in both the latest release and nightly builds. You can see them all if you search for "station" in Bort
![image](https://github.com/user-attachments/assets/7ec47323-30b7-43d1-a154-fe930cfd4f85)

**Comment by Petedcc** [comment]
Ahh id been searching jett/store... got them thanks very much !
