### ISSUE TITLE
Allowing the export of display items

### ISSUE THREAD

**Issue by zahnatom** [DCS-Skunkworks/dcs-bios#1007]
### Version

- [X] I am using the latest version

### Aircraft

Any

### Control

MFDs, HUDs, etc

### Description

In the lua console(and lua in general) it's possible to get strings from MFDs, the HUD, etc through "list_indication(N)". It would be great to have this be exportable to arduinos to replicate certain texts without having to export the entire screen.
Here's an example: on aircraft that have MFDs, the buttons have some text associated with them, which is displayed on the screen. which i'd like to export to make interactive touch buttons instead of hardware buttons. end goal is to have this work for the Eurofighter Typhoon which has those buttons with screens but thats not here yet :p

### Screenshots

![image](https://github.com/user-attachments/assets/0668e1d7-a64a-4cec-8a92-b2fed5f53073)
![image](https://github.com/user-attachments/assets/1aadcaaa-da7a-4e80-a44f-74a455e25372)
![image](https://github.com/user-attachments/assets/966865e5-1c75-4f1f-aea5-01b18a0b105f)
![image](https://github.com/user-attachments/assets/14f52bef-105f-47c5-95a3-9d533202bc16)
![image](https://github.com/user-attachments/assets/638ade4b-cb1d-457a-b0f7-fab7f1d57552)
![image](https://github.com/user-attachments/assets/3c73c0fb-5611-4649-af39-611c3bdb590a)

### Additional context

i put some code snippits for the f-15e in the discord https://discord.com/channels/533342958712258572/1287518951709999287

**Comment by charliefoxtwo** [comment]
So one thing I'll mention is that the format by which these are exported is not uniform across all modules. All modules name their data differently - so I don't know that there's a uniform solution we could use here, other than something like every module exports items 1-100 of each display but I don't see that being a very useful solution.

This is something we could consider in a limited scope on a module-by-module basis.

**Comment by charliefoxtwo** [comment]
Bios isn't really designed in a manner that would be extensible like that. I mean you could technically go in and edit the lua to export whatever you want, but I don't know that there are any additional tools I can provide to make that easier.
