### ISSUE TITLE
AH64d PLT / CPG power lever Idle

### ISSUE THREAD

**Issue by onepunchndown** [DCS-Skunkworks/dcs-bios#1010]
### Version

- [X] I am using the latest version

### Aircraft

AH-64D

### Control

Power Lever Quadrant

### Description

I have written to and been in contact with ED about the missing Lua script within the clickabledata.lua
But we need a command for the idle point on the power lever finger lifts. Both right and left.

### Screenshots

[Untitled document.pdf](https://github.com/user-attachments/files/17335117/Untitled.document.pdf)

**Comment by charliefoxtwo** [comment]
Was that not addressed by https://github.com/DCS-Skunkworks/dcs-bios/issues/999?

**Comment by charliefoxtwo** [comment]
Due to no response, I'm closing this as a duplicate. Feel free to reopen if you believe that's not the case.
