### ISSUE TITLE
F-14 Pilot Radio Remote Display Tests not functional

### ISSUE THREAD

**Issue by elorock13** [DCS-Skunkworks/dcs-bios#1020]
### Version

- [X] I am using the latest version

### Aircraft

F-14B

### Control

F-14/PLT_UHF_DISPLAY_TEST
F-14/PLT_VUHF_DISPLAY_TEST

### Description

F-14/PLT_UHF_DISPLAY_TEST has no effect when sent
F-14/PLT_VUHF_DISPLAY_TEST triggers RIO_UHF_DISPLAY_TEST instead

### Steps to reproduce

Load into hot-start F-14
Press assigned pushbutton for UHF Test (DcsBios::Switch2Pos pltUhfDisplayTest("PLT_UHF_DISPLAY_TEST", 9);), no effect
Press assigned pushbutton for U/VHF Test (DcsBios::Switch2Pos pltVuhfDisplayTest("PLT_VUHF_DISPLAY_TEST", 5);), test button on RIO UHF remote display is depressed instead

### Expected behavior

UHF and U/VHF remote display test buttons respectively should have been depressed

### Additional context

F-14/RIO_UHF_DISPLAY_TEST works as expected

**Comment by charliefoxtwo** [comment]
Thanks for reporting this! This will be fixed in the next nightly build.
