### ISSUE TITLE
CDU Display bug : SYS -> EGI

### ISSUE THREAD

**Issue by sjstein** [DCS-Skunkworks/dcs-bios#114]
DCS-BIOS does not send the memory space mapping for the A10C-II CDU display when pilot selects SYS (function key) and then EGI (LSK-L1). 

When this screen is entered in-game, no memory updates within the CDU display range (0x11C0 - 0x12B0) are broadcast.

Upon returning from the screen, the updates continue normally.

Below is a memory snapshot of the "frozen" screen:

```
11c0 20535953202020202020202020302020202044352f423120 |  SYS         0    D5/B1 
11d8 202020202020202020202020202020202020202020202020 |                         
11f0 bb4547492020494e532056204344552056204c41535445ab | ·EGI  INS V CDU V LASTE·
1208 2020202020204750532056204d4243205620202020202020 |       GPS V MBC V       
1220 bb494e5320204d534e2056204454532056202048415253ab | ·INS  MSN V DTS V  HARS·
1238 202020202043414443205620445453415320562020202020 |      CADC V DTSAS V     
1250 bb47505320484152532056202020202020204454534153ab | ·GPS HARS V       DTSAS·
1268 202020204c41535445205620202020202020202020202020 |     LASTE V             
1280 bb5245494e495420202020202020202020205245534554ab | ·REINIT           RESET·
1298 5bb620202020202020202020202020205d2050312f322020 | [·              ] P1/2  
```

**Comment by sjstein** [comment]
I will try to understand how the DCS-BIOS functions enough to see if I can debug, however if anyone out there has experience in working within the DCS-BIOS lua script, any and all help is much appreciated. I don't even know where to begin tbh.

**Comment by WarLord211** [comment]
same on my side. Tha a-10 was the first and the developer is unreachable.
so i look for help and show what we can do.

**Comment by WarLord211** [comment]
is this a new screen? not in the old A-10C?

**Comment by sjstein** [comment]
> is this a new screen? not in the old A-10C?

I just verified that it is the same in the old A-10C. It does have the CDU and it exhibits the same bug.

**Comment by sjstein** [comment]
There is a completely separate JSON file located at `~/Scripts/DCS-BIOS/doc/json/A-10C_CDU.json` - For me, it is pretty unreadable (and very large). It does appear to have some structure embedded within.

**Comment by WarLord211** [comment]
there is no documentation about it. we have to look ourselfs how this works and were the bug is.
sorry i cant give you more advice atm

**Comment by sjstein** [comment]
Ha - not your fault!

I'll try to reverse the process a bit to determine how it works fundamentally. Maybe a good place to start would be to try and add a "new" aircraft just to see how it behaves.

**Comment by sjstein** [comment]
I understand that, but I'm confused at the basics of even how the UDP packets are constructed and sent. 

I'm currently digging around in `~/Scripts/DCS-BIOS/lib/TextDisplay.lua` with regards to the text display

**Comment by WarLord211** [comment]
i asumme its in the (BIOS)A-10C.lua with the readouts for the CDU. and the data for this is anywere in the cockpit section of the A-10 module itself

**Comment by charliefoxtwo** [comment]
I did some migration work in this area so that the apache's EUFD could utilize the same code, so I'm probably the most familiar dev with this stuff at this point.

I can play around with it when I get some time, but my guess is that either the page's name doesn't match up with what's in the `A-10C_CDU.json` file or that file just doesn't have the definitions for that specific page, in which case they'll have to be added.

One way to debug this would be to log the value of `displayPage` in `TextDisplay.lua`. Basically, add `BIOS.log(displayPage)` right after this, and then verify that the page logged actually exists in `A-10C_CDU.json`. https://github.com/DCSFlightpanels/dcs-bios/blob/70bbc2dc41312e46aa503f67769570d09bfb07f1/Scripts/DCS-BIOS/lib/TextDisplay.lua#L37

**Comment by charliefoxtwo** [comment]
I'm not sure if there's much we can do to fix this currently. This seems to be an issue in the A-10 luas from ED. They incorrectly defined this page so it doesn't update the page display name when the page is changed.

In the meantime, for anybody who comes across this, this issue can be worked around by modifying the A-10 lua `Cockpit\Scripts\CDU\device\CDU.lua`.

Changing line 114 to the text below will resolve the issue in my testing.
```lua
set_page_name({CDU_MASTER,CDU_SYS,CDU_EGI1}                        ,"CDU_EGI")
```

**Comment by WarLord211** [comment]
should this changed in the repo?
