### ISSUE TITLE
Keys with spaces

### ISSUE THREAD

**Issue by charliefoxtwo** [DCS-Skunkworks/dcs-bios#188]
#### `R_MC_LOW ALT_L`
https://github.com/DCSFlightpanels/dcs-bios/blob/3e40d24f17901c5c0f69afa735c0f2fe5dfa3717/Scripts/DCS-BIOS/lib/F-15E.lua#L1141
#### `R_MC_TF FAIL_L`
https://github.com/DCSFlightpanels/dcs-bios/blob/3e40d24f17901c5c0f69afa735c0f2fe5dfa3717/Scripts/DCS-BIOS/lib/F-15E.lua#L1143
#### `MCP_CKT BKR_L`
https://github.com/DCSFlightpanels/dcs-bios/blob/3e40d24f17901c5c0f69afa735c0f2fe5dfa3717/Scripts/DCS-BIOS/lib/MB-339.lua#L371

**Comment by WarLord211** [comment]
Thanks.
Internal fixed upload with next open beta patch

**Comment by WarLord211** [comment]
F-15 uploaded

**Comment by WarLord211** [comment]
is it good now?

**Comment by charliefoxtwo** [comment]
looks good to me!
