### ISSUE TITLE
Some F-15E switches not working in dcs bios

### ISSUE THREAD

**Issue by rocketeer998** [DCS-Skunkworks/dcs-bios#223]
I have hooked up all switches in DCS to physical switches. Some in the left panel and front console don't work. Could these be bugs in the dcs bios release for the F-15E, or because this module is in early release in DCS so we can blame it all on it still being in early access stage?

Left console
- RICP panel, all 3 dual encoders
- Sensor panel, radar altitude switch

Front Console
- warning tone silence button
- emergency landing gear handle, push pull function
- Fuel Qty panel, bingo knob only turns clockwise
- instrument gauges, altimeter, ADI, clock etc only clockwise

**Comment by WarLord211** [comment]
the BIOS names from that switches would good. im not that familiar with the F-15

**Comment by rocketeer998** [comment]
maybe the radar alt switch works for other modules, but it does not work for the F-15E at the moment.

**Comment by WarLord211** [comment]
How should the f15 Radar switch work on other modules?

**Comment by rocketeer998** [comment]
i thought you were testing radar alt switch found on other modules. I don't mean to expect the F-15's radar alt to work in other modules.

DcsBios::Switch3Pos fSRdrAlt("F_S_RDR_ALT", PIN_A, PIN_B);

I'm using dcs-bios-0.7.49. Control reference shows this version even though i downloaded 0.10.0.
DCS 2.8.8.43704

**Comment by WarLord211** [comment]
0.10 has no f-15 and is was outdated.
I asume you use open beta but latest release of bios. Master branch would be a better Option. Instruction in the doc folder.

I testen the Radar alt switch of the f-15 with bort and works as it should. The other you mentioned I didnt found due idk the f15.

You give me the bios namens like F_S_RDR_ALT
And I can test the others

**Comment by rocketeer998** [comment]
lol I thought 0.10.0 is the latest, as suggested by youtubers who told me to go here. 
https://github.com/dcs-bios/dcs-bios
I just downloaded it 3 months ago. It still says it's the latest today

Then I searched around and saw this
https://github.com/DCSFlightpanels/dcs-bios
Is this what you mean by master branch?
It says New DCS Stable Update 2.8.7
wow that's much bigger number than 0.10.0
Clicking on it now it says v0.7.49
This is confusing. But anyway I'd download this one and install it, see what happens.

**Comment by rocketeer998** [comment]
thanks for letting me know there is a more up to date version from the fork, I chose the wrong one.

i installed the 0.7.49. Now the radar alt, 3 dual encoders on the RICP panel, and the push pull switch for emergency landing gear work. Great progress!

But the following still don't work
//FRONT Landing Gear Lever (Landing Gear Warning Tone Silence Switch )
DcsBios::Switch2Pos fLgGearTone("F_LG_GEAR_TONE", PIN);

//FRONT Fuel Bingo Selection 
DcsBios::Potentiometer fFuelBingo("F_FUEL_BINGO", PIN);
I also tried the advanced, encoder version
DcsBios::RotaryEncoder fFuelBingo("F_FUEL_BINGO", "-3200", "+3200", 7, 8);
it doesn't matter which way you turn the physical knob, the bingo needle on the fuel quantity panel will only rotate clockwise.

//FRONT Altitude adjust (altimeter)
DcsBios::RotaryEncoder fFiAltAdj("F_FI_ALT_ADJ", "-3200", "+3200", PIN_A, PIN_B);
same thing, the needle only rotates clockwise

For the ADI, it only moves between 45 and 90 degress, whether you push to turn or just turn
DcsBios::Potentiometer fFiBakAdiCageKnob("F_FI_BAK_ADI_CAGE_KNOB", PIN);
DcsBios::RotaryEncoder fFiBakAdiCageKnob("F_FI_BAK_ADI_CAGE_KNOB", "-3200", "+3200", 7, 8);

**Comment by WarLord211** [comment]
0.10 was an update from this version, but the developer is gone. We moved on with the old versiiion and hold it uptodate.
For the master branch thing look here: https://github.com/DCSFlightpanels/dcs-bios/blob/master/Scripts/DCS-BIOS/doc/DCS-BIOS-FLIGHTPANELS_Install%20Guide.pdf

i taek by time a look at these switches

**Comment by WarLord211** [comment]
fix uploaded

**Comment by rocketeer998** [comment]
wow u are fast. I'd test them out. Thanks!

**Comment by rocketeer998** [comment]
So I have to download dcs bios again? I see the latest is Aug 12, not Sep 17.

**Comment by WarLord211** [comment]
Yes Master branch. How to? Pls Look at the instructions I posted before.

**Comment by rocketeer998** [comment]
Warlord you fixed everything! Landing Gear Warning Tone Silence button, Fuel Bingo Selection, altimeter, ADI cage knob now all tested working. Great job!

We are fixing and improving this module.

Three other weird observations. 

1. Armament Jettison. In the manual it says the left 3 selections FF, MANUAL RET and ALTN REL are an alternate release mechanism, not part of the jettison system. Yet if you mouse over the knob you can rotate it to all positions, including the first three. For dcs bios, I can only make it work from OFF to AG, the 4th to 7th positions. It ignores the first three.

//FRONT Armament Jettison Selector 
const byte fArmJettSelPins[7] = {PIN_0, PIN_1, PIN_2, PIN_3, PIN_4, PIN_5, PIN_6};
DcsBios::SwitchMultiPos fArmJettSel("F_ARM_JETT_SEL", fArmJettSelPins, 7);



2. FUEL QTY panel. the selection knob works only from 2nd position FEED all the way to CONF TANK. if you mouse over it, the first position is a spring loaded action. even if we didn't build a spring mechanism physically, it should let us turn to the first position. at the moment first position doesn't work.

//FRONT Fuel Totalizer Selector
const byte fFuelTotalPins[7] = {30, 31, 32, 33, 34, 35, 36};
DcsBios::SwitchMultiPos fFuelTotal("F_FUEL_TOTAL", fFuelTotalPins, 7);



3. AMAD and AMAD Left lights not working
//FRONT AMAD Fire Light (red)
DcsBios::LED fAmadFireL(0x9318, 0x4000, 2);

//FRONT AMAD Left Engine Fire Light (red)
DcsBios::LED fAmadLEngFireL(0x9318, 0x8000, 3); 

The following are working. When i click on test light switch on the right console light panel they light up
//FRONT AMAD Right Engine Fire Light (red)
DcsBios::LED fAmadREngFireL(0x931a, 0x0100, 4);

//FRONT AMAD Left Engine Burn Throu Light (red)
DcsBios::LED fAmadLEngBurnL(0x931a, 0x0200, 5);

//FRONT AMAD Right Engine Burn Throu Light (red)
DcsBios::LED fAmadREngBurnL(0x931a, 0x0400, 6);

Now in the latest control reference version 0.7.50, the LED code changed to like this below. these don't even compile.
DcsBios::LED fAmadFireL(F_15E_F_AMAD_FIRE_L, PIN);
DcsBios::LED fAmadLEngBurnL(F_15E_F_AMAD_L_ENG_BURN_L, PIN);
DcsBios::LED fAmadLEngFireL(F_15E_F_AMAD_L_ENG_FIRE_L, PIN);

The ones with alphanumberic numbers like 0x931a, 0x0200 at least will compile for LEDs.

**Comment by WarLord211** [comment]
1 and 2 areWIP - i look into it when i have time
How has you tested the Lights? with and software (bort) or with LEDs? not that the LED broken.

for the compiling error theres a new arduino library wich support these lines
https://github.com/DCS-Skunkworks/dcs-bios-arduino-library/releases/tag/0.3.9

**Comment by WarLord211** [comment]
Again to the Lights:
With LT Test switch on the right (not familiar with F-15) BIOS gives all lights a 1 -> that means BIOS shows what the cockpit shows.

**Comment by WarLord211** [comment]
Switches fixed tested and uploaded to master

**Comment by WarLord211** [comment]
everything works?

**Comment by rocketeer998** [comment]
I downloaded the latest code. Imported the latest arduino 0.3.9 zip file. still couldn't compile. Then I added the files in it to dcs bios arduino library master folder. now I could compile the new code like 
DcsBios::LED fAmadFireL(F_15E_F_AMAD_FIRE_L, PIN); 
and not old one like 
DcsBios::LED fAmadREngFireL(0x931a, 0x0100, PIN);

fAmadREngFireL and the two burn through ones. Now all of them with the new type of code don't work, except the last one fAmadREngBurnL which works the opposite. it is prelit. When I press the test toggle, it goes off when it should light up.

DcsBios::LED fAmadFireL(F_15E_F_AMAD_FIRE_L, 2);
DcsBios::LED fAmadLEngFireL(F_15E_F_AMAD_L_ENG_FIRE_L, 3);
DcsBios::LED fAmadREngFireL(F_15E_F_AMAD_R_ENG_FIRE_L, 4);

DcsBios::LED fAmadLEngBurnL(F_15E_F_AMAD_L_ENG_BURN_L, 5);
DcsBios::LED fAmadREngBurnL(F_15E_F_AMAD_R_ENG_BURN_L, 6);

So all 5 LEDs are not working.

**Comment by rocketeer998** [comment]
For the Armament Jettison rotary switch, first 3 positions now working. Thanks!

**Comment by rocketeer998** [comment]
For the Fuel Totalizer Selector, now first position BIT that didn't work now it works.

2nd position is FEED
3rd position is INTERNAL WING

When I rotate from position 1 to 7, all work fine.

When I rotate counter clockwise from 7 to 1, when I get to 3, it will not go to 2. I will have to repeat it. toggle between 2 and 3. then i can go to 2 from 3. I tried this a few times.

So now one can rotate to position 1, which is an improvement.
And going from 1 to 7 is smooth.
But going from 7 to 1 should not require repeated toggle from 3 to 2 to 3 to 2. should be a one time turn.

Thanks for all the hard work and help!

**Comment by rocketeer998** [comment]
Using the old type of code, the last 3 lights with 0x931a work. 

The first two with 0x9318 don't work.

**Comment by rocketeer998** [comment]
Any chance on making the LED code work?

**Comment by charliefoxtwo** [comment]
@WarLord211 could you take a look at this? I don't own the F15, otherwise I would.

**Comment by jdahlblom** [comment]
@WarLord211 can you check this?

**Comment by WarLord211** [comment]
The led work via bort.

The jumpin is confirmed but atm I have no solution. But I havent testen it with the last Patch.

**Comment by jdahlblom** [comment]
Where are we with this? Is there any specific tests I can do?

**Comment by rocketeer998** [comment]
The CAS panel has a few bugs.

the pitch, yaw, roll 3-way toggles all flip to down position when physical toggle is flipped up. and down again when flipped down. In DCS they are either down or in the center only. they are down when they should be up.

For the trim light, it doesn't turn on when trim button is pressed.

old code
DcsBios::LED fCasTrimL(0x93ba, 0x0100, pin);

new code
DcsBios::LED fCasTrimL(F_15E_F_CAS_TRIM_L, pin);

both old and new code for LED not working.

I believe all 3 CAS toggles above, and the trim light were working in the past. I've tested every button and switch and light in the F-15E. Only the AMAD panel have some LED not working.
Now CAS partially not working too.

**Comment by jdahlblom** [comment]
@rocketeer998 Create a new issue for new problems.

**Comment by jdahlblom** [comment]
>I've tested every button and switch and light in the F-15E. Only the AMAD panel have some LED not working. Now CAS partially not working too.
Can this issue be closed then?

**Comment by rocketeer998** [comment]
given that some switches that used to work now no longer do, I don't know how many other switches got broken somehow with new code. I test switches few months ago and have been waiting for the fix the the few LEDs in AMAD panel. now 3 switches and a light are no longer working in CAS panel. Maybe more will appear. We'd need to retest all panels. I'd report if I find more issues. I'd also independently test using different switches and different arduino mega from the existing ones connected to my cockpit to make sure it's not the problem with the existing set up.

**Comment by charliefoxtwo** [comment]
Keep in mind that sometimes switches will break when the module developer (in this case, Razbam) makes changes to how their module works behind the scenes. We try to stay on top of these changes but it's difficult to catch everything and we'll inevitably miss some.

Either way, if you could let us know which switches do not work as you're doing your tests that would be incredibly helpful!

**Comment by rocketeer998** [comment]
Engine panel. when you press the light test toggle in the Internal Light Panel, the JFS light comes on in DCS. but physical switch does not. Same as the CAS panel I reported yesterday, when you press the trim button, the trim light does not come on. It does in DCS game. and code is there. I just tested these using new physical switches and light indicators and a separate Mega. Both JFS light and CAS trim light still not working.

For the three toggles (pitch, roll, yaw) in CAS panel I reported above, they are 3 way toggles. I said above they keep going to down (OFF) position. Upon careful observation, it is not always down. it is skipping the center RESET position. when I flip it to center, it went to the UP (ON) position, which from an angle it looks like the center position, since it is higher than the down position. So in DCS these toggles are just switching between ON and OFF position even using the mouse to click them. they are skipping the center RESET position! If these toggles are mean to be just ON and OFF without a center RESET position, then it should be a 2 way switch instead of a 3 way switch. DCS Bios has them as 3 way switches. Not sure if it has since changed to a 2 way switch in the game? or it is a bug in dcs that makes it skip the center position.

**Comment by charliefoxtwo** [comment]
Could you file a new issue for the engine panel issues you've mentioned? Also it greatly helps if you're able to include the bios control names, as we're not always familiar with the aircraft.

I believe the CAS panel issues are being tracked [here](https://github.com/DCS-Skunkworks/dcs-bios/issues/525)

@jdahlblom was asking if the initial switch problems reported in this issue have been resolved. Are these switches working as expected? If so we should close this issue and track problems with the other switches in separate issues. It's much easier for us to keep track of what is and isn't working this way (and easier for others to discover if they have a similar issue as well).
> Left console
>
>    RICP panel, all 3 dual encoders
>    Sensor panel, radar altitude switch
>
> Front Console
>
>    warning tone silence button
>    emergency landing gear handle, push pull function
>    Fuel Qty panel, bingo knob only turns clockwise
>    instrument gauges, altimeter, ADI, clock etc only clockwise

**Comment by rocketeer998** [comment]
I've answered the CAS issues in the link you provided.

I'd file a new issue for the engine panel.

As for the list above, I believe they have been solved but I'd need to test them again for sure since the trim light in CAS was working and now not so.

I'd keep you guys posted.

**Comment by jdahlblom** [comment]
I am closing this issue as it is too broad or encompassing.
