### ISSUE TITLE
P-51D/ACCELEROMETER_VALUE not working for negative values

### ISSUE THREAD

**Issue by charliefoxtwo** [DCS-Skunkworks/dcs-bios#248]
The output for `ACCELEROMETER_VALUE` in the P-51 is an integer representation of the g value on the accelerometer. However, bios does not support sending negative values, so this will never send anything below zero. Additionally, bios can only send whole integer values, which are not entirely useful here as the integer range of the gauge is fairly small (-5 through +12), with the operational range of the aircraft smaller still.

Code in question:
https://github.com/DCS-Skunkworks/dcs-bios/blob/9ad8630d462681d5b67d308f6a908e06a10a2469/Scripts/DCS-BIOS/lib/modules/aircraft_modules/P-51D.lua#L280-L284

My suggestion here would be to drop the `-5` offset and change the multiplier to `17000`. This would give much more granularity to the gauge. The end user would have to do the math on their end to calculate the actual G value (`(value / 1000) - 5`) but at least they would be able to get a more useful value out of it, and negative values wouldn't simply report as 0.

**Comment by WarLord211** [comment]
why not simply make a float out of it?

**Comment by charliefoxtwo** [comment]
There is `ACCELEROMETER_MAIN`, which has the gauge value. Perhaps we should just remove `ACCELEROMETER_VALUE` as it doesn't have any real utility?

**Comment by WarLord211** [comment]
This is one of the oldest modules. I never did something like this Code and also had nobody ask for it. It was there and I have left it there

**Comment by charliefoxtwo** [comment]
This sort of thing appears in a few places. I agree it doesn't have much value. We can remove them and replace them with empty placeholders in the memory map so it doesn't mess up the addresses for everybody else if you want.

https://github.com/DCS-Skunkworks/dcs-bios/blob/9ad8630d462681d5b67d308f6a908e06a10a2469/Scripts/DCS-BIOS/lib/AJS37.lua#L350-L401
https://github.com/DCS-Skunkworks/dcs-bios/blob/9ad8630d462681d5b67d308f6a908e06a10a2469/Scripts/DCS-BIOS/lib/Bf-109K-4.lua#L209-L306
https://github.com/DCS-Skunkworks/dcs-bios/blob/9ad8630d462681d5b67d308f6a908e06a10a2469/Scripts/DCS-BIOS/lib/F-86F%20Sabre.lua#L339-L461
https://github.com/DCS-Skunkworks/dcs-bios/blob/9ad8630d462681d5b67d308f6a908e06a10a2469/Scripts/DCS-BIOS/lib/modules/aircraft_modules/P-51D.lua#L172-L284

**Comment by charliefoxtwo** [comment]
@WarLord211 what would you like to do here - remove them, or leave them? If we leave them, what would you like to do about the ones that don't work as expected, like the P-51D `ACCELEROMETER_VALUE`?

**Comment by WarLord211** [comment]
stay with what work. delete what not work, without placeholders the following items are made by me without requests.
So i think the impact of the useres are negligible.
