### ISSUE TITLE
Mig-15 ARC5_BAND duplicate controls

### ISSUE THREAD

**Issue by charliefoxtwo** [DCS-Skunkworks/dcs-bios#258]
One of these should be renamed

https://github.com/DCS-Skunkworks/dcs-bios/blob/f835e10aa966553dc5a88958982f80c5ee502591/Scripts/DCS-BIOS/lib/modules/aircraft_modules/MiG-15bis.lua#L189
https://github.com/DCS-Skunkworks/dcs-bios/blob/f835e10aa966553dc5a88958982f80c5ee502591/Scripts/DCS-BIOS/lib/modules/aircraft_modules/MiG-15bis.lua#L200

**Comment by WarLord211** [comment]
defineTumb("ARC5_BAND_SW", 29, 3004, 177, 0.5, { 0, 1 }, nil, false, "ARC5", "ARC-5 Frequency Band Switch") 

were my solution
