### ISSUE TITLE
Some RotaryEncoders does not work OK with AJS37

### ISSUE THREAD

**Issue by DanVigg** [DCS-Skunkworks/dcs-bios#322]
Hi ,
I try to use Rotary Encoders for some functions in AJS37 together with DCS-Bios and Arduino
1. Altimeter works OK can change value in both direktions
2. Backupaltimeter works only in one direction
3. Airspeed Index jumps some steps then locks , can´t move forward or backward
4. Group selector one direction
5. Base selector one direction
<img width="551" alt="Rotary issue" src="https://github.com/DCS-Skunkworks/dcs-bios/assets/89347866/1f704baf-cb49-41ce-a460-141ced26f403">
Regards Dan

**Comment by charliefoxtwo** [comment]
Backup altimeter was fixed in #311 and should go live in the nightly build today. Others require further investigation.
