### ISSUE TITLE
F/A 18C UFC_COMM1_CHANNEL_SELECT & UFC_COMM2_CHANNEL_SELECT identifier re-used

### ISSUE THREAD

**Issue by jdahlblom** [DCS-Skunkworks/dcs-bios#350]
```Master branch```

Looking at the json there is one control of each and the output is empty which isn't correct.
Unit testing didn't find these since the profile hasn't been migrated yet to Module.

```
defineRotary("UFC_COMM1_CHANNEL_SELECT", 25, 3033, 124, "Up Front Controller (UFC)", "COMM 1 Channel Select Knob")
defineRotary("UFC_COMM2_CHANNEL_SELECT", 25, 3034, 126, "Up Front Controller (UFC)", "COMM 2 Channel Select Knob")
defineFixedStepInput("UFC_COMM1_CHANNEL_SELECT", 25, 3033, {-0.03, 0.03}, "Up Front Controller (UFC)", "COMM 1 Channel Select Knob")
defineFixedStepInput("UFC_COMM2_CHANNEL_SELECT", 25, 3034, {-0.03, 0.03}, "Up Front Controller (UFC)", "COMM 2 Channel Select Knob")
```

**Comment by WarLord211** [comment]
since the rotary works i would delete the other 2. But a Spacer should be set the avoid the address change

**Comment by charliefoxtwo** [comment]
When a control is duplicated, it's the last entry that is used as that overwrites the previous entries. As such, the fixed step input would be the control currently being used. Do we want to continue with this one?

**Comment by WarLord211** [comment]
then delete the rotary,
