### ISSUE TITLE
DCS BIOS stops transmitting instrument data in HUD View

### ISSUE THREAD

**Issue by lesthegringo** [DCS-Skunkworks/dcs-bios#413]
DCS Bios works fine in cockpit view (using DCS Bios for the A10C), but when I switch to HUD View using l-alt+f1, a number of instruments including but not limited to the digital clock and UHF radio panel no longer have the information transmitted. Once you return to the cockpit view the data flow is resumed so it is not a disconnection

**Comment by charliefoxtwo** [comment]
This may be a dcs thing - I know export also stops when on the f10 map page and _to my knowledge_ there's nothing we can do about that - but I'll do some testing to confirm.

**Comment by charliefoxtwo** [comment]
@jdahlblom could you test this with insight? Maybe go into hud mode and see if you can still pull any data from the model.

**Comment by jdahlblom** [comment]
In HUD mode the ```UHF_PRESET_SEL``` works with insight.

**Comment by lesthegringo** [comment]
Is insight a tool for use in game? The way I read it is was just for diagnostics

**Comment by jdahlblom** [comment]
Just for debugging and finding out how the various APIs function and argument values etc.

**Comment by lesthegringo** [comment]
ok, that's what I thought

If it is not possible to get DCS BIOS to transmit data in HUD mode, is there a way to 'hide' the cockpit so that it isn't visible? Maybe being able to locate the eye position just in front of the cockpit, the HUD can probably be rendered as a viewport using monitorsetup.lua

**Comment by charliefoxtwo** [comment]
@lesthegringo in hud mode is it just certain items that aren't being exported or is no data being exported at all?

**Comment by lesthegringo** [comment]
It's certain items, VincVega on the DCS forums found this 
https://dcs-bios.a10c.de/docs/v0.5.1/userguide.html#_aircraft_specific_notes

 However I have found that the digital clock is not exported either and there are probably other undocumented ones we haven't found yet

**Comment by charliefoxtwo** [comment]
@jdahlblom could you test and try to get a device with insight while in hud mode? Perhaps the CMSP, indication `7`?

**Comment by jdahlblom** [comment]
Yeah will do. Insight broke down after the last dcs-bios updates, must be name collision. I will add full path to require first.

**Comment by jdahlblom** [comment]
list_indication(7) works in both views.

**Comment by lesthegringo** [comment]
Hi guys, while it would be ideal to have all the instruments exported whether or not they are displayed, a viewport workaround does work. It's up to you guys if you want to close this using that as a solution, let me know

**Comment by lesthegringo** [comment]
Sure, let me post the solution in the DCS home cockpits forum and link it

**Comment by lesthegringo** [comment]
As promised

https://forum.dcs.world/topic/334998-hud-view-seems-to-disable-some-dcs-bios-devices/#comment-5305039

**Comment by jdahlblom** [comment]
Looking further with insight it was easy to observer using the ```CLOCK_SS``` control. This value comes from ```list_indication(4)```. 
A few samples with HUD Mode :
* ```list_indication(1)``` works
* ```list_indication(2)``` works
* ```list_indication(3)``` stops updating
* ```list_indication(4)``` stops updating
* ```list_indication(5)``` works

**Comment by charliefoxtwo** [comment]
As this seems to be a DCS bug and/or feature, I'm going to go ahead and close this issue. We definitely don't do anything specific in bios based on the view - I guess in certain aircraft certain objects get culled and are no longer updated depending on the view setting.
