### ISSUE TITLE
FW 190 A-8 Anton,  switch BMB_FUSE_SEL doesn't work

### ISSUE THREAD

**Issue by Botik85** [DCS-Skunkworks/dcs-bios#470]
FW 190 A-8 Anton,  switch BMB_FUSE_SEL doesn't work

**Comment by charliefoxtwo** [comment]
@WarLord211 or @jdahlblom could you take a look at this one? It works fine in the D9 but I don't own the A8.

**Comment by Botik85** [comment]
Now it works fine. Thank you very much!
