### ISSUE TITLE
FW 190 A-8 Anton, switch CB_GUNS_COWL_OFF executes an incorrect command

### ISSUE THREAD

**Issue by Botik85** [DCS-Skunkworks/dcs-bios#471]
FW 190 A-8 Anton, switch CB_GUNS_COWL_OFF executes CB_GUNS_IN_OFF command. This is an error.

**Comment by charliefoxtwo** [comment]
@WarLord211 or @jdahlblom could you take a look at this one? I only have the D9 and it doesn't appear to have this circuit breaker.

**Comment by Botik85** [comment]
Now it works fine. Thank you very much!

**Comment by Botik85** [comment]
Now it works fine. Thank you very much!
