### ISSUE TITLE
F-15E wrong device id for TF Auto Flyup switch (F_BH_FLYUP_CVR and F_BH_FLYUP)

### ISSUE THREAD

**Issue by SlipHavoc** [DCS-Skunkworks/dcs-bios#476]
The F-15E.lua script file references device 17 for the TF Auto Flyup switch, but it should be 65.  If you change these lines:

defineToggleSwitch("F_BH_FLYUP_CVR", **17**, 3522, 522, "Front Left Bulkhead Panel", "FRONT Flyup Enable Switch Cover")
defineToggleSwitch("F_BH_FLYUP", **17**, 3523, 523, "Front Left Bulkhead Panel", "FRONT Flyup Enable Switch")

to this:

defineToggleSwitch("F_BH_FLYUP_CVR", **65**, 3522, 522, "Front Left Bulkhead Panel", "FRONT Flyup Enable Switch Cover")
defineToggleSwitch("F_BH_FLYUP", **65**, 3523, 523, "Front Left Bulkhead Panel", "FRONT Flyup Enable Switch")

the flyup switch and cover commands work correctly.  See <dcs install folder>\Mods\aircraft\F-15E\Cockpit\clickabledata.lua, line 309 and 310, references devices.TFR.

**Comment by WarLord211** [comment]
good find
