### ISSUE TITLE
MosquitoFBMkVI: redesigning the bios removed the working commands.

### ISSUE THREAD

**Issue by Saylors** [DCS-Skunkworks/dcs-bios#491]
I'm using **DCSFlightpanels_x64_4.11.0** 
and latest version "**dcs-bios-master**" https://github.com/DCS-Skunkworks/dcs-bios .

When running my profile for MosquitoFBMkVI it gives errors about missing commands. The commands worked before (flew in September). 
![2023-11-07_233744](https://github.com/DCS-Skunkworks/dcs-bios/assets/50142231/f8de8630-305a-4320-8bb3-6f7606bb335d)
![2023-11-07_233710](https://github.com/DCS-Skunkworks/dcs-bios/assets/50142231/ad1b563c-5f65-4f04-bdea-97b9e608c471)

I tried to remove the commands mentioned in the screenshots from my profile - but further errors appear with the rest of the commands (which all used to work).
I read https://github.com/DCS-Skunkworks/dcs-bios/commit/366ecc6640b1a26077276fcc26ce14ae2965a087 - are all Mosquito commands now unused? Or do all commands now have different names and should I create a new profile again with a set of new commands?
Attaching my profile for MosquitoFBMkVI.
[Flight Panel MosquitoFBMkVI (Saylors).zip](https://github.com/DCS-Skunkworks/dcs-bios/files/13307129/Flight.Panel.MosquitoFBMkVI.Saylors.zip)

**Comment by jdahlblom** [comment]
True, new version does not accept hyphen in the control identifier. Just rename the control name and you are good to go. I am guessing it is PORT_CUT_OUT.

Identifier must now be in uppercase, can contain underscore, must start with letter.

**Comment by Saylors** [comment]
> True, new version does not accept hyphen in the control identifier. Just rename the control name and you are good to go. I am guessing it is PORT_CUT_OUT.
> 
> Identifier must now be in uppercase, can contain underscore, must start with letter.

Replaced as you suggested - it worked! Thank you!
![Снимок экрана 2023-11-09 193503](https://github.com/DCS-Skunkworks/dcs-bios/assets/50142231/809e832d-83d5-4135-ada6-9532f8fa72de)
