### ISSUE TITLE
Question: building flightstick from scratch 

### ISSUE THREAD

**Issue by sanderma** [DCS-Skunkworks/dcs-bios#493]
Hi awesome folk!

I’m a DCS-bios (and arduino) n00b so please be gentle 😅

I’m converting a broken (as in all electronics are gone) T16000m stick to an F-16 stick (custom 3d printed handle) and have some questions I couldn’t find myself.

- Should I use DCS-bios for the hall sensor input, or will that introduce latency (can’t find how such a massive amount of input is handled)
- I have an mcp23017 to save space in the handle, which method/lib should I use to make that work (or what should I do instead)?
- Should I use multiple arduinos?

I hoped I would be able to sort this out myself, but apparently you guys make building incredibly complicated stuff look easy 😂

Thanks for making this possible for the community and thanks in advanced for helping me out!

Greets,
Sanderma

**Comment by charliefoxtwo** [comment]
First, bios can only be used for clickable items - that generally excludes all hotas controls in most aircraft, as well as the stick input itself. Bios really can't help you here. 

I think you'd really want to create an HID device here or similar with DirectX inputs.

**Comment by sanderma** [comment]
Ah nice! That makes total sense btw.
I'll create the stick logic with a specialised solution, and then proceed with the MFD's via dcs-bios 👍 

Thanks for taking the time to answering my (in hindsight) obvious question!

**Comment by schnoog** [comment]
@sanderma 
I also have an F-16 Stick with 1 MCP23017 included. All attached to a Arduino Micro Pro. 

Until this commit: https://github.com/schnoog/joystick_F16_sidestick/tree/a6815a0b8b6306e7c320214fe435f6df5ce1d547
I used the analog input (which was provided by 2 AS5600 hall sensors)
(Switched to a DIY force sensing base some month ago)

**Comment by sanderma** [comment]
Thanks a lot @schnoog !
That helps a lot. Going to get a lot of inspiration from your code 👍
