### ISSUE TITLE
A-10C CMSP Switch3Pos

### ISSUE THREAD

**Issue by TheWarthogProject** [DCS-Skunkworks/dcs-bios#495]
Since the latest DCS patch I noticed the four toggle switches on the A-10C CMSP don't work anymore. Displays and buttons still work, just the Switch3Pos doesn't work. Bort shows no movement registered when I flick them in game as well. Tested it on my workbench pc without the latest patch and no problems there. Weird.

**Comment by charliefoxtwo** [comment]
When you tested the old version that worked, did you see the output values in bort as well? I'm doing some testing now and I've gotten output working again but it doesn't seem to use the values the code was originally written for (and the latest patch just migrated that original code).

**Comment by charliefoxtwo** [comment]
I've gotten input working more or less, but oddly enough it won't go directly from OFF to MENU - you have to do setstate(2) twice (or setstate(1) setstate(2)). Not sure what's going on there.

**Comment by charliefoxtwo** [comment]
No problem! It seems the issue here is that ED updated the underlying values in 2.9.1.48335. I've got a PR up which brings bios back in line. Would be interesting to know if they changed any others as well 🤔

**Comment by TheWarthogProject** [comment]
Cheers! Ill keep an eye out for anything else not working.
