### ISSUE TITLE
IFEI string buffer left-aligned (merged from dcs-bios/dcs-bios)

### ISSUE THREAD

**Issue by charliefoxtwo** [DCS-Skunkworks/dcs-bios#50]
I just came across [this issue](https://github.com/dcs-bios/dcs-bios/issues/235) in the base dcs-bios repo. I'm curious - is this something that should be fixed? I've worked around it in my usages, but it is frustrating when bingo 500 sends as `500__` but is supposed to be displayed right-aligned on the IFEI as `__500` (underscores indicate spaces, since github markdown trims spaces in code formatting).

**Comment by WarLord211** [comment]
please name the Plane. i dont know all planes well.

**Comment by charliefoxtwo** [comment]
Sorry! This is the F/A-18C Hornet. The strings in this case are the ones displayed on the IFEI (Integrated Fuel & Engine Indicator).

**Comment by WarLord211** [comment]
i cant format strings. i can give them a space of the expected amount of numbers and more i cant do. (as far as i find in the documentations)

**Comment by charliefoxtwo** [comment]
Is it possible to just modify (or duplicate) the `coerce_nil_to_string` method to add some additional string processing (basically, it should just be a matter of finding the index of the first space character, then moving the substring of spaces to the beginning of the string)?

Here's a pretty rudimentary example of a method that could be called

```
local function move_spaces(value)
    local start = string.find(value, " ")
    if (start == nil) then return value end
    return string.sub(value, start) .. string.sub(value, 1, start - 1)
end
```

Many of the strings on the IFEI already call that `coerce_nil_to_string` method so it seems like you could wrap that and send the result to `move_spaces` or something right?

**Comment by WarLord211** [comment]
maybe. but thats a little beyond my knowledge. if you got this to work, i will integrade it.

**Comment by charliefoxtwo** [comment]
Cool, I'll take a look and report back. Feel free to assign this issue to me.

**Comment by WarLord211** [comment]
any News?

**Comment by charliefoxtwo** [comment]
Nothing yet - it's still on my todo list.
