### ISSUE TITLE
AJS-37 Viggen radio FR22 : Can't get digital inputs to work

### ISSUE THREAD

**Issue by F6veson** [DCS-Skunkworks/dcs-bios#516]
Hi!
I have built a FR22 unit for a future simpit of AJS-37 Viggen.
I have managed to get both Base and Group selectors to work with DCS World open beta.
Even got the outputs for selected channels to work and they are displayed on each Oled-displays on the FR22 unit.

I use this kind of code snippets in my Arduino-program for the other twenty pushbuttons :
 DcsBios::Switch2Pos fr22ChannelH("FR22_CHANNEL_H", PIN);
DcsBios::Switch2Pos fr22ChannelAg("FR22_CHANNEL_AG", PIN);
etc
But it doesn't work. Nothing happens at the FR22 unit in the DCS World open beta cockpit,

Anybody who have the same problem or have a solution for it.....

**Comment by charliefoxtwo** [comment]
To rule out a code issue, have you tried pushing the buttons or reading the button values with [Bort](https://github.com/DCS-Skunkworks/Bort) and verifying whether that works?

**Comment by F6veson** [comment]
Yes I have tried pushing my FR22 buttons and read value with Bort.  Bort does not register the inputs. I have measured voltage on the pins I use and they change from +4,9V to 0 when I push a button. I have even tried to invert so when push a button there is a high level on the input pin.
I have tried to set the buttons in DSC cockpit from Bort with each of the functions (set, toggle). But none of the buttons (H, 1, 2 ,3 ,- ,A/G ,B, C/F, C2, D/E, 0-9) seems to work. The digital status of these buttons don´t changes in Bort and they don´t changes graphically in DCS cockpit.

**Comment by jdahlblom** [comment]
Sitting and testing now via ctrlref and dcs-bios seems broken.
```FR22_BASE``` string output is changing itself all the time.
```FR22_CHANNEL_AG``` is not working via ctrlref and clicking in the cockpit works. ctrlref shows then the correct value.

**Comment by jdahlblom** [comment]
@F6veson Check master branch. Added fixed controls there right now.

**Comment by jdahlblom** [comment]
The ```FR22_BASE``` string output is still wacky but the uint result is correct.

**Comment by F6veson** [comment]
It´s working now!
Many thanks for your help!
