### ISSUE TITLE
F-18C Standby Compass [BUG]

### ISSUE THREAD

**Issue by Sturmbock** [DCS-Skunkworks/dcs-bios#520]
**DCS-BIOS version**
0.7.49

**DCS-BIOS Control**
F-18C Standby Compass Heading ```SBY_COMPASS_HDG```

**Describe the bug**
On the F-18C Standby Compass, the values output in 'newValue' do not span the entire range 0-65335 as expected, and as is the case on the A-10C. This results in the calculated heading bearing no resemblance to the on screen Standby Compass.
I have tested the 'newValue's being output by the A-10C and the F-18C. The A-10’s values were as expected, but the F-18’s were not:

A-10C (compass heading and output newValue)
North – 65499, East – 49164, South - 33166, West – 16290
Note, The newValue output spans the complete range 0-65335 going anti-clockwise around the compass
---------
F-18C  (compass heading and output newValue)
North – 65438, East – 40923, South – 48924, West - 57379 
Note, The newValue output goes anti-clockwise around the compass, but does not span the complete number range 0-65335, rather it’s restricted to a subset of that – I would suggest causing the exhibited behaviour.

**To Reproduce**
1. Start A-10C or F-18C mission
2. Steer the aircraft around on the ground (or in the air) to various compass headings
3. Monitor the output of 'newValue'
4. See above for my results

**Expected behaviour**
F-18C should be similar to A-10C and provide a 'newValue' that covers the complete range 0-65335

**Screenshots**
N/A

**Additional context**

**Comment by jdahlblom** [comment]
Fix added to ```master branch``` or download ```nightly build``` tomorrow.

**Comment by Sturmbock** [comment]
I can confirm that the 'newValues' for heading now seem to have corrected the problem. However, the values for pitch and bank were working ok before and the change you have made to all three seems to have broken these two.  If I change these two back to -1 all three now work correctly.

**Comment by jdahlblom** [comment]
Thanks, I will change those values back.

**Comment by jdahlblom** [comment]
Pitch and bank for compass now reverted. You can close this issue if all is OK.

**Comment by Sturmbock** [comment]
All now working
