### ISSUE TITLE
CAS panel has a few bugs

### ISSUE THREAD

**Issue by jdahlblom** [DCS-Skunkworks/dcs-bios#525]
The CAS panel has a few bugs.

the pitch, yaw, roll 3-way toggles all flip to down position when physical toggle is flipped up. and down again when flipped down. In DCS they are either down or in the center only. they are down when they should be up.

For the trim light, it doesn't turn on when trim button is pressed.

old code
DcsBios::LED fCasTrimL(0x93ba, 0x0100, pin);

new code
DcsBios::LED fCasTrimL(F_15E_F_CAS_TRIM_L, pin);

both old and new code for LED not working.

I believe all 3 CAS toggles above, and the trim light were working in the past. I've tested every button and switch and light in the F-15E. Only the AMAD panel have some LED not working.
Now CAS partially not working too.

_Originally posted by @rocketeer998 in https://github.com/DCS-Skunkworks/dcs-bios/issues/223#issuecomment-1945496008_

**Comment by jdahlblom** [comment]
Tried the toggles in `ctrlref` and I am not sure of the behavior. Sending `2` consequently toggles between `ON / OFF`.
Although all 3 positions works from `ctrlref` (dcs-bios).

![Screenshot 2024-02-15 131927](https://github.com/DCS-Skunkworks/dcs-bios/assets/10453261/46da92ac-baa2-480d-87db-173da10b535c)
![Screenshot 2024-02-15 132031](https://github.com/DCS-Skunkworks/dcs-bios/assets/10453261/764f167e-545f-489a-bcaf-fd2107c5cf6f)

**Comment by rocketeer998** [comment]
So I filed a bug with ED forum. Someone explained that these 3 toggles are OFF AND ON position only. The middle RESET is spring loaded to ON. So I'd have to use a 2 way ON OFF toggle instead. So consider these 3 toggles working correctly.

Just need to fix the trim light. when pressed it lights up in the game but not the physical light indicator. I tried wiring it to 5 different indicators. I guess dcs bios is not triggering a signal to the light indicator. For both the old and new LED code.

**Comment by jdahlblom** [comment]
> I guess dcs bios is not triggering a signal to the light indicator. For both the old and new LED code.

Works just fine with:
* DCS-BIOS Nightly Build
* DCSBIOSBridge
* Verified using BIOSBuddy

```DcsBios::LED fCasTrimL(F_15E_F_CAS_TRIM_L_AM, greenLed);```

You have something wrong with your setup.

**Comment by rocketeer998** [comment]
This CAS light is now working when you press the press the physical T/O trim button or use mouse to click on the button. But I want to let you know which code worked.

oldest code didn't work
DcsBios::LED fCasTrimL(0x93ba, 0x0100, pin);

then new code didn't work
DcsBios::LED fCasTrimL(F_15E_F_CAS_TRIM_L, pin);

latest dcs bios downloaded code still didn't work, which is same as your code above.
DcsBios::LED fCasTrimL(F_15E_F_CAS_TRIM_L_AM, pin);
This line cannot even compile in Arduino.
![bios error](https://github.com/DCS-Skunkworks/dcs-bios/assets/145094080/9ea2c182-c6bc-4f9a-85b9-18941c006df1)



Then I grabbed this code from Bort
DcsBios::LED fCasTrimL(0x93ae, 0x0100, pin);
This is the one that works.

**Comment by charliefoxtwo** [comment]
@maciekish any idea why this wouldn't compile?

**Comment by jdahlblom** [comment]
![macros](https://github.com/DCS-Skunkworks/dcs-bios/assets/10453261/e122b300-b278-4bbb-b0e4-ed22637bc71f)

**Comment by jdahlblom** [comment]
> Then I grabbed this code from Bort DcsBios::LED fCasTrimL(0x93ae, 0x0100, pin); This is the one that works.

Good, you solved it, closing this issue.
