### ISSUE TITLE
[BUG] No Route To Host Error

### ISSUE THREAD

**Issue by verlotl2000** [DCS-Skunkworks/dcs-bios#527]
**DCS-BIOS version**
2.8.7

**DCS-BIOS Control**
N/A

**Describe the bug**
I get the following error when running the connect-serial-port.cmd file and entering my comport:
![image](https://github.com/DCS-Skunkworks/dcs-bios/assets/116467108/4eea3b89-a555-424a-9409-64cf8e181507)

here's the message in text:
2024/02/16 22:23:27 socat[404] E setsockopt(5, 0, 12, {0x0a32ffef,0x00000000}, 8): No route to host

**To Reproduce**
Steps to reproduce the behavior example:
Run connect-serial-port.cmd

**Expected behavior**
It should just connect so I can use my arduino board.

**Screenshots**

**Additional context**
Just installed a bunch of windows updates, then it stopped working.

**Comment by verlotl2000** [comment]
> This is an issue with socat and your networking and I’m no specialist there. What happens if you run “tracert localhost” on the command line?

Hi, thx for the reply. This is what I get when running tracert localhost.

![image](https://github.com/DCS-Skunkworks/dcs-bios/assets/116467108/ec13858e-d7e4-4ca1-b308-82be846190cc)

**Comment by jdahlblom** [comment]
Did you get this working?
