### ISSUE TITLE
[BUG] Compilation Error for External Aircraft Model Lights, Strobe Lights etc for KA50

### ISSUE THREAD

**Issue by a3igner** [DCS-Skunkworks/dcs-bios#529]
v0.7.5 latest and open beta

External Aircraft Model

Using any of the External Aircraft Model LED references yields compilation error.

The strobe light and others throw similar errors at compilation time.

```
DcsBios::LED extPositionLightLeft(Ka_50_EXT_POSITION_LIGHT_LEFT_AM, PIN);
N:\Arduino\ExternalLights\ExternalLights.ino:16:35: error: 'Ka_50_EXT_POSITION_LIGHT_LEFT_AM' was not declared in this scope
 DcsBios::LED extPositionLightLeft(Ka_50_EXT_POSITION_LIGHT_LEFT_AM, 13);
                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
N:\Arduino\ExternalLights\ExternalLights.ino:16:35: note: suggested alternative: 'Ka_50_EXT_POSITION_LIGHT_LEFT_ADDR'
 DcsBios::LED extPositionLightLeft(Ka_50_EXT_POSITION_LIGHT_LEFT_AM, 13);
                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                   Ka_50_EXT_POSITION_LIGHT_LEFT_ADDR\
exit status 1
Compilation error: 'Ka_50_EXT_POSITION_LIGHT_LEFT_AM' was not declared in this scope
```

**Comment by charliefoxtwo** [comment]
Are you only encountering this error for the external lights, for all KA-50 controls, or for all controls in all aircraft?

**Comment by a3igner** [comment]
> Are you only encountering this error for the external lights, for all KA-50 controls, or for all controls in all aircraft?

It seems only for those External Aircraft Model. Other ones I tried works, like Comms Power and  ABRIS display for instance, but I can't obviously test all of them.  

But this External Aircraft Model Lights for the F16C is also broken btw.

**Comment by charliefoxtwo** [comment]
@maciekish any idea what could be going on here? I checked my header file locally and these constants do exist

**Comment by maciekish** [comment]
> @maciekish any idea what could be going on here? I checked my header file locally and these constants do exist

I think something went wrong when generating Addresses.h+docs last time and it hasn't been fixed since. Ill try to take a look at it soon.

**Comment by charliefoxtwo** [comment]
I know there was a problem not too long ago with generating the addresses file and I thought I fixed it, but maybe this is something else. https://github.com/DCS-Skunkworks/dcs-bios/pull/510

**Comment by maciekish** [comment]
> v0.7.5 latest and open beta
> 
> External Aircraft Model
> 
> Using any of the External Aircraft Model LED references yields compilation error.
> 
> The strobe light and others throw similar errors at compilation time.
> 
> ```
> DcsBios::LED extPositionLightLeft(Ka_50_EXT_POSITION_LIGHT_LEFT_AM, PIN);
> N:\Arduino\ExternalLights\ExternalLights.ino:16:35: error: 'Ka_50_EXT_POSITION_LIGHT_LEFT_AM' was not declared in this scope
>  DcsBios::LED extPositionLightLeft(Ka_50_EXT_POSITION_LIGHT_LEFT_AM, 13);
>                                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> N:\Arduino\ExternalLights\ExternalLights.ino:16:35: note: suggested alternative: 'Ka_50_EXT_POSITION_LIGHT_LEFT_ADDR'
>  DcsBios::LED extPositionLightLeft(Ka_50_EXT_POSITION_LIGHT_LEFT_AM, 13);
>                                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>                                    Ka_50_EXT_POSITION_LIGHT_LEFT_ADDR\
> exit status 1
> Compilation error: 'Ka_50_EXT_POSITION_LIGHT_LEFT_AM' was not declared in this scope
> ```

Are you using the Arduino library from https://github.com/DCS-Skunkworks/dcs-bios-arduino-library or from https://github.com/DCS-Skunkworks/dcs-bios/tree/master/Programs/dcs-bios-arduino-library ?

**Comment by a3igner** [comment]
> > v0.7.5 latest and open beta
> > External Aircraft Model
> > Using any of the External Aircraft Model LED references yields compilation error.
> > The strobe light and others throw similar errors at compilation time.
> > ```
> > DcsBios::LED extPositionLightLeft(Ka_50_EXT_POSITION_LIGHT_LEFT_AM, PIN);
> > N:\Arduino\ExternalLights\ExternalLights.ino:16:35: error: 'Ka_50_EXT_POSITION_LIGHT_LEFT_AM' was not declared in this scope
> >  DcsBios::LED extPositionLightLeft(Ka_50_EXT_POSITION_LIGHT_LEFT_AM, 13);
> >                                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> > N:\Arduino\ExternalLights\ExternalLights.ino:16:35: note: suggested alternative: 'Ka_50_EXT_POSITION_LIGHT_LEFT_ADDR'
> >  DcsBios::LED extPositionLightLeft(Ka_50_EXT_POSITION_LIGHT_LEFT_AM, 13);
> >                                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> >                                    Ka_50_EXT_POSITION_LIGHT_LEFT_ADDR\
> > exit status 1
> > Compilation error: 'Ka_50_EXT_POSITION_LIGHT_LEFT_AM' was not declared in this scope
> > ```
> 
> Are you using the Arduino library from https://github.com/DCS-Skunkworks/dcs-bios-arduino-library or from https://github.com/DCS-Skunkworks/dcs-bios/tree/master/Programs/dcs-bios-arduino-library ?

Yes of course. Can you not reproduce this error in your setup ? 

Which versions of the library do you use? 
I downloaded the latest one from skunkworks

**Comment by a3igner** [comment]
> I believe the question was about _which_ of the two linked libraries is the one you're using - they're both in the skunkworks org, but one is in the dcs-bios repo and one is in a separate dcs-bios-arduino-library repo

Aha In my error finding process I thought it had to do with either one, so I switched libraries to eliminate this possibility too. But it's the same issue in both libraries the separate one as well as the one packaged in the dns-bios subfolder.

**Comment by maciekish** [comment]
@charliefoxtwo This is the Addresses.h file that works with the current control-reference.html:

https://github.com/DCS-Skunkworks/dcs-bios/blob/master/Scripts/DCS-BIOS/doc/Addresses.h

Why this wasnt included in releases and the other repos i dont know. Either i never submitted a PR or it was never merged. Should i make a PR for the dcs-bios-arduino-library? I don't want to update the zip files myself as im not familiar with the process and could miss something, so if someone else has to update the releases/zip files, maybe they can update Addresses.h as well while they're on it?

@a3igner If you take the above file and place it inside your Documents\Arduino\libraries\dcs-bios-arduino-library-master\src\internal folder, overwriting the one that is there, it should compile fine.

**Comment by charliefoxtwo** [comment]
If it's on master then it should be included in the nightly releases - is that not the case?

As for dcs-bios-arduino-library, who usually handles those releases? I don't know anything about any of the arduino stuff so it's definitely not me 😅

**Comment by maciekish** [comment]
It is in this one, wasn't aware there are nightlies. https://github.com/DCS-Skunkworks/dcs-bios/releases/tag/latest However, thats the DCS-World LUA lib and its only there because it was generated. Arduino IDE won't pick it up from there. It needs to be updated in dcs-bios-arduino-libraries and when you download the default release of DCS-BIOS its linking to the stable release which is not updated.

**Comment by a3igner** [comment]
> @charliefoxtwo This is the Addresses.h file that works with the current control-reference.html:
> 
> https://github.com/DCS-Skunkworks/dcs-bios/blob/master/Scripts/DCS-BIOS/doc/Addresses.h
> 
> Why this wasnt included in releases and the other repos i dont know. Either i never submitted a PR or it was never merged. Should i make a PR for the dcs-bios-arduino-library? I don't want to update the zip files myself as im not familiar with the process and could miss something, so if someone else has to update the releases/zip files anyway, maybe they can update Addresses.h as well while they're on it?
> 
> @a3igner If you take the above file and place it inside your Documents\Arduino\libraries\dcs-bios-arduino-library-master\src\internal folder, overwriting the one that is there, it should compile fine.

thanks I will try. but in my documents folder there is only ~\Documents\Arduino\libraries\DCS-BIOS-FP-Form\src\internal. which has an addresses file in there. should I overwrite that one then? or where do I find the library folder?

**Comment by maciekish** [comment]
> > @charliefoxtwo This is the Addresses.h file that works with the current control-reference.html:
> > https://github.com/DCS-Skunkworks/dcs-bios/blob/master/Scripts/DCS-BIOS/doc/Addresses.h
> > Why this wasnt included in releases and the other repos i dont know. Either i never submitted a PR or it was never merged. Should i make a PR for the dcs-bios-arduino-library? I don't want to update the zip files myself as im not familiar with the process and could miss something, so if someone else has to update the releases/zip files anyway, maybe they can update Addresses.h as well while they're on it?
> > @a3igner If you take the above file and place it inside your Documents\Arduino\libraries\dcs-bios-arduino-library-master\src\internal folder, overwriting the one that is there, it should compile fine.
> 
> thanks I will try. but in my documents folder there is only ~\Documents\Arduino\libraries\DCS-BIOS-FP-Form\src\internal. which has an addresses file in there. should I overwrite that one then? or where do I find the library folder?

Yes that looks correct.

**Comment by charliefoxtwo** [comment]
> It is in this one, wasn't aware there are nightlies. https://github.com/DCS-Skunkworks/dcs-bios/releases/tag/latest However, thats the DCS-World LUA lib and its only there because it was generated. Arduino IDE won't pick it up from there. It needs to be updated in dcs-bios-arduino-libraries and when you download the default release of DCS-BIOS its linking to the stable release which is not updated.

This stable vs openbeta problem I'm assuming will go away with the update that's supposed to be coming tomorrow, since they're moving to a single version. We'll just have to figure out how we want to handle it...

**Comment by a3igner** [comment]
Oh I see. What I did was download the stable version DCS BIO 0.7.49 and opened the control reference html there and that actually shows 

DcsBios::LED extStrobeTail(0x4562, 0x0800, 2);
DcsBios::LED extStrobe(0x197c, 0x0400, 3);

and that compiles fine! Thanks I think this should work now.  The Latest release is broken or not working. So someone should remove it or make it inactive/or update it to avoid people running into the same issue again. cheers!

**Comment by maciekish** [comment]
> Oh I see. What I did was download the stable version DCS BIO 0.7.49 and opened the control reference html there and that actually shows
> 
> DcsBios::LED extStrobeTail(0x4562, 0x0800, 2); DcsBios::LED extStrobe(0x197c, 0x0400, 3);
> 
> and that compiles fine! Thanks I think this should work now. The Latest release is broken or not working. So someone should remove it or make it inactive/or update it to avoid people running into the same issue again. cheers!

That works too, but when addresses change (and they do) you will have to go through all your files and manually update the addresses so i would recommend you to use the Addresses.h.

**Comment by jdahlblom** [comment]
Can we close this?

**Comment by a3igner** [comment]
Yes can!———————————————————————Am 07.03.2024 um 14:40 schrieb Jerker Dahlblom ***@***.***>:﻿
Can we close this?
