### ISSUE TITLE
AV8B ODU Text displays not showing any value in DCS BIOS 

### ISSUE THREAD

**Issue by SimoGiuby** [DCS-Skunkworks/dcs-bios#556]
AV8B "ODU option 1/2/3/4/5 Text" do not display any value in DCS BIOS (both in BORT or physical LCD screen).
"ODU option 1/2/3/4/5 SELECT" and every other UFC displays work correctly.

Using DCS OpenBeta, DCS Bios Nightly release and no other extra programs.

![ODU Error](https://github.com/DCS-Skunkworks/dcs-bios/assets/166137329/b75905c8-3baf-42ef-a547-c33e4fc9a2da)

**Comment by charliefoxtwo** [comment]
@jdahlblom I don't own the harrier - could you take a look at this one?

**Comment by jdahlblom** [comment]
Yup

**Comment by jdahlblom** [comment]
Yes it isn't showing the information. I managed to get the ODU to show information by pressing TACAN.
This is then picked up by dcs-insight:
```
-----------------------------------------
ODU_DISPLAY

-----------------------------------------
ODU_Option_1_Text
T/R
-----------------------------------------
ODU_Option_2_Text
RCV
-----------------------------------------
ODU_Option_3_Text
A/A
-----------------------------------------
ODU_Option_4_Text
X
-----------------------------------------
ODU_Option_5_Text
TONE
```

**Comment by jdahlblom** [comment]
I get this:
```

1: 
2: T/R
3: RCV
4: A/A
5: X
6: TONE
0: 6
ODU_Option_2_Text: RCV
ODU_Option_3_Text: A/A
ODU_Option_5_Text: TONE
ODU_DISPLAY: 
ODU_Option_1_Text: T/R
ODU_Option_4_Text: X
```

But the lua expects this:
```
ODU_Option_1_TEXT
```

That is apparently case sensitive. Changing it to `ODU_Option_1_Text` and it outputs the data.

**Comment by jdahlblom** [comment]
But what are those `AV8BNA_ODU_5_SELECT` controls? I can't see them in the ```list_indication```.

**Comment by jdahlblom** [comment]
I got `ODU_Option_2_Slc` to show, seems to work as mentioned.

**Comment by SimoGiuby** [comment]
Hey Jdahlblom, thank you so much for lookimg into it!
Will there be an updated DCS-BIOS with the fix incorporated? Or how should I change my own LUA file (I wouldn't know where to start to be honest)? (Apologies for the total ignorance!)

The "Select" part of the code was working already, as you found out.

Thank you so much again and congratulations of the great job you guys do!

**Comment by jdahlblom** [comment]
It will be merged shortly.

**Comment by jdahlblom** [comment]
It is merged now so you can download master branch.

**Comment by jdahlblom** [comment]
If this solved your problem you can close this issue.

**Comment by SimoGiuby** [comment]
I am abroad at the moment, will check as soon as I have access to my laptop and close it. It might take a couple of days though...

Thank you very much again!

**Comment by SimoGiuby** [comment]
All working correctly, closing this issue now.

Thank you again for your help and your amazing work guys!

**Comment by jdahlblom** [comment]
Your welcome, thanks.
