### ISSUE TITLE
Implementation of user friendly DCS BIOS Skunkworks installation and BORT interface

### ISSUE THREAD

**Issue by Rambowski** [DCS-Skunkworks/dcs-bios#559]
Dear developers,

First, I would like to thank you for all your time and efforts you put into this project to satisfy the DCS community.
 
As many of us I am using the DCS BIOS Skunkworks to drive my home pit. It has been a while before I even realized that the old DCS BIOS I was using was not even supported anymore by the maker. I realized that after some of my panels just stopped working. It has been a challenge for me get throughout the installation of DCS BIOS Skunkworks and after I managed to place the folders into the right spot on my hard drive a realized that my Google Chrome doesn't support the DCS BIOS app anymore. 

Few months later I found the BORT extension however there is no installation file into the zip folder anymore. Today, I see there is a DCS Skunkworks update but I have no idea how to update it. Do I have to overwrite all the files once again or just install the updated files? As you can imagine sometimes all of this make it pretty difficult to stay "ahead"of the game. 

My question to you guys...is there any chance to implement an automatic installation and DCS BIOS interface like we had this before with the "old" DCS BIOS program, but without Google app/extensions?  If not is there any possibility to simplify and clarify the DCS BIOS Skunkworks installation or include BORT into the installation file (or so something else which could work in a browser)? 

I am desperately looking forward for your answers.

Best regards,
Rambowski

**Comment by jdahlblom** [comment]
Just time for a short (non) answer right now. Back tomorrow. 

Check DCS-BIOS folder for:
* Start.html
* User Guide

Check the Wiki on the homepage.

**Comment by charliefoxtwo** [comment]
> Today, I see there is a DCS Skunkworks update but I have no idea how to update it. Do I have to overwrite all the files once again or just install the updated files?

We highly recommend you overwrite all files to be safe

**Comment by charliefoxtwo** [comment]
Installers can be nice. Installing srs is very convenient. But yeah, it's yet another item to maintain, so I don't see it happening for a while (if ever).
