### ISSUE TITLE
AH-64D Apache Manual Tracker Left Right not changing in game[BUG]

### ISSUE THREAD

**Issue by Zultan1234** [DCS-Skunkworks/dcs-bios#563]
**DCS-BIOS version**

0.8.0

**DCS-BIOS Control**

AH-64D/CPG_RHG_MAN_TRK_L_R

Right hand grip:  only Manual Tracker left right has an issue. Up down works well

**Describe the bug**

The interaction from bort to DCS is not working only for the left and right function CPG_RHG_MAN_TRK_L_R.

It works well for the Up and Down.

**To Reproduce**

1. Open bort
2. Open DCS
3. Load any mission (I used instant action live fire in the Apache missions)
4. Go CPG slot (press 2 in my case)
5. Enable TEDAC display by pressing TADS (its like a 4 option switch) on the Right hand grip
6. Try slewing the display up and down and left and right using Manual Tracker (White stick next to TADS)
7. now open bort and try to update the **CPG_RHG_MAN_TRK_L_R** to value 0 or 2 which should move the display left or right 
8. Trye it with up and down in bort and it should work.

**Expected behavior**

CPG_RHG_MAN_TRK_L_R changed to 0 or 2 should slew the TADS left or right

**Screenshots**

<img width="998" alt="image" src="https://github.com/DCS-Skunkworks/dcs-bios/assets/166924225/72f701bd-bc95-467c-9008-e5683a389e2c">

Output works well

Thanks for your attention

**Comment by charliefoxtwo** [comment]
Huh. I took a look at the bios code compared to the dcs apache lua and I honestly don't see anything wrong here. This is a weird one. When testing, I actually saw the control flash over to the left/right for a frame or two before immediately recentering, so it's like it's not sticking for some reason, but up/down is. I'm not yet sure why this would be the case, since the controls seem to be defined identically on the ED side.

**Comment by Zultan1234** [comment]
> Huh. I took a look at the bios code compared to the dcs apache lua and I honestly don't see anything wrong here. This is a weird one. When testing, I actually saw the control flash over to the left/right for a frame or two before immediately recentering, so it's like it's not sticking for some reason, but up/down is. I'm not yet sure why this would be the case, since the controls seem to be defined identically on the ED side.
> 
> This also seems like it should maybe be defined as an axis.


I didn't notice it flash at all. When i did it, it didn't move. Could be because of my fps being lower so it skipped the frame where it flashes.

**Comment by Zultan1234** [comment]
> > Huh. I took a look at the bios code compared to the dcs apache lua and I honestly don't see anything wrong here. This is a weird one. When testing, I actually saw the control flash over to the left/right for a frame or two before immediately recentering, so it's like it's not sticking for some reason, but up/down is. I'm not yet sure why this would be the case, since the controls seem to be defined identically on the ED side.
> > This also seems like it should maybe be defined as an axis.
> 
> I didn't notice it flash at all. When i did it, it didn't move. Could be because of my fps being lower so it skipped the frame where it flashes.

**Comment by charliefoxtwo** [comment]
Alright, I took another look and was able to get this working. I don't know _why_ it needed to be changed, but it should be fixed now. Give the latest nightly build a try (should build and release in ~10 minutes or so) - and let me know if it works!
