### ISSUE TITLE
A-10C ILS frequency does not display on 7 segment anymore

### ISSUE THREAD

**Issue by rocketeer998** [DCS-Skunkworks/dcs-bios#564]
In the past it used to work like this.
![image](https://github.com/DCS-Skunkworks/dcs-bios/assets/145094080/f0781276-98b5-4b53-bc59-028ec2d8fab6)
![image](https://github.com/DCS-Skunkworks/dcs-bios/assets/145094080/2ce4fd26-b915-479c-905f-2015dcc9f179)

Using 0x12d8 it will still compile now but it becomes blank on the 7 segment display except for decimal point.
![image](https://github.com/DCS-Skunkworks/dcs-bios/assets/145094080/d565f599-3650-4bf9-bf01-c04974a33f29)

Now in latest dcs bios, it uses new type of naming convention, which just like those in F-15E LEDs code, they don't compile.
![image](https://github.com/DCS-Skunkworks/dcs-bios/assets/145094080/dce13a80-7435-4c22-a153-366e40fe1299)

Bort also shows the new naming convention.
![image](https://github.com/DCS-Skunkworks/dcs-bios/assets/145094080/fa3a8ba5-f133-422a-939c-90d85efeaad5)

If I try to use the new code, change from 0x12d8 new A_10C_ILS_FREQUENCY_S_A. I will get 'no declared in scope' error, as when I used any new naming convention for F-15E LED code.
![image](https://github.com/DCS-Skunkworks/dcs-bios/assets/145094080/9cd30c92-f59b-4f66-b97e-ed8a3b9b6a51)

Something seems to have changed in dcs bios such that old code 0x12d8 doesn't carry the ILS frequency anymore, yet we can't compile arduino using the new code  A_10C_ILS_FREQUENCY_S_A.

**Comment by charliefoxtwo** [comment]
@maciekish, could you help with this user having issues compiling with the constants?

Meanwhile @rocketeer998, you can disable address constants in bort with the checkbox at the top - try that, as it's possible the address changed.
![image](https://github.com/DCS-Skunkworks/dcs-bios/assets/30303272/9704f2b9-263b-4109-b78b-45e7ce26c046)

**Comment by maciekish** [comment]
@charliefoxtwo Not declared in scope means Addresses.h is probably not included in the Arduino sketch. It was recently decided in the staff channel on Discord that Adresses.h should not be distributed with the Arduino-library. Not sure if documentation was updated for this change.

**Comment by maciekish** [comment]
@rocketeer998 try this https://github.com/DCS-Skunkworks/dcs-bios/wiki/Addresses.h Final location and mode of distribution for Addresses.h is still not set in stone.

**Comment by rocketeer998** [comment]
ok I declared the address in my saved games path. Now I can use the macro and ILS frequency shows up now.

Thanks all you guys!
