### ISSUE TITLE
F-14/PLT_RADAR_ALT_TEST_LIGHT not working

### ISSUE THREAD

**Issue by elorock13** [DCS-Skunkworks/dcs-bios#566]
**DCS-BIOS Control**
F-14/PLT_RADAR_ALT_TEST_LIGHT

**Describe the bug**
Value does not respond to state in-game, neither in BORT nor with a connected LED

**To Reproduce**
Steps to reproduce the behavior example:
1. Start F-14 mission
2. Turn on Radar Altimeter and press BIT
3. Nothing happens

**Expected behavior**
Value in BORT goes from 0 to 1, connected LED lights up
Argument corresponding to F-14/PLT_RADAR_ALT_TEST_LIGHT in MV2 is 681, not 19108

**Comment by charliefoxtwo** [comment]
relevant lua:
https://github.com/DCS-Skunkworks/dcs-bios/blob/b0d4982d3cf7c4ae80eba02bcd40b93bf5eb680d/Scripts/DCS-BIOS/lib/modules/aircraft_modules/F-14.lua#L881-L882

@elorock13 did you happen to notice if `PLT_RADAR_ALT_LIGHT` works as expected?

**Comment by elorock13** [comment]
Yes, `PLT_RADAR_ALT_LIGHT` (19107) works

**Comment by jdahlblom** [comment]
`Argument corresponding to F-14/PLT_RADAR_ALT_TEST_LIGHT in MV2 is 681, not 19108`
What does this mean? MV2? 681?

**Comment by jdahlblom** [comment]
```RADALT_GreenTest = 681,``` works. 
Loaded both models into ModelViewer. It says in both that ```19108``` isn't used. Both works with ```681```. Will change draw arg to ```681```.

**Comment by elorock13** [comment]
> `Argument corresponding to F-14/PLT_RADAR_ALT_TEST_LIGHT in MV2 is 681, not 19108` What does this mean? MV2? 681?

ModelViewer 2. The IDs of the "Arguments" you can edit in that software correspond to the ones in the F-14.lua (ie if you change the value for Argument 19107, the corresponding `PLT_RADAR_ALT_LIGHT` lights up). Im guessing dcs-insight does something similar.

**Comment by elorock13** [comment]
> `RADALT_GreenTest = 681,` works. Loaded both models into ModelViewer. It says in both that `19108` isn't used. Both works with `681`. Will change draw arg to `681`.

Perfect, thank you!

**Comment by jdahlblom** [comment]
@charliefoxtwo will review the PR today and then it will be merged.

**Comment by jdahlblom** [comment]
@elorock13 it is in the master branch now and tomorrow in the nightly release.

**Comment by elorock13** [comment]
Thank you very much
