### ISSUE TITLE
Mi-24 collective

### ISSUE THREAD

**Issue by HaunterSix** [DCS-Skunkworks/dcs-bios#571]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by HaunterSix** [comment]
I dont know how it works here so i write  a comment instead. 
There is no collective category in fork, no axis, no buttons. I am building my own collective and could not find the code/adress anywhere in fork. Is it possible to fix that or add that?

**Comment by jdahlblom** [comment]
IIRC HOTAS and collectives etc should be configured via DCS directly. There are no DCS-BIOS controls for these.

**Comment by jdahlblom** [comment]
Whatever PCB you are using should have a HID interface that is detected by DCS.

**Comment by HaunterSix** [comment]
So it is not possible for me to lets say take a potentiometer and use it as the collective axis with Arduino and fork? Any other way to do this?

**Comment by jdahlblom** [comment]
As a reference, when my pedals broke and I replaced the PCB with a Bodnar board and it showed up in DCS and it was a straightforward thing to get it working again.

**Comment by HaunterSix** [comment]
Bodnar bbi 64? I read about those and was thinking about getting those instead of Arduino

**Comment by jdahlblom** [comment]
> So it is not possible for me to lets say take a potentiometer and use it as the collective axis with Arduino and fork? Any other way to do this?

Yes it is, you just have to have the correct board to connect your pot to.

**Comment by jdahlblom** [comment]
> Bodnar bbi 64? I read about those and was thinking about getting those instead of Arduino

I don't remember anymore, this was 10 yrs ago. I don't own any sim equipment anymore. But bodnar have (had at least) boards that you just connected whatever you want to and they work perfectly with Windows as a HID device.

**Comment by HaunterSix** [comment]
What is the correct board? Sorry for the questions but i am very new to the programming prat

**Comment by jdahlblom** [comment]
I will have to lure someone else here to help you with the details. I don't want to give you the wrong advice. Meanwhile you can describe how many buttons, axis there are. So that the board has enough capacity to accommodate every function.

**Comment by HaunterSix** [comment]
Thank u, u must be the most honest person i have come across.
There are 2 axis, one for the throttle, one for the collective itself.
3 switches, 4 push buttons, and a joystick hat wich i believe should also be a axis, or i am Thinking about using some sort of hat switch

**Comment by No1sonuk** [comment]
I have been lured. :)
The Bodnar board you'd need is one with analogue inputs.  The BBI boards don't have analogue interfaces.
From your descrition, the BU0836A 12-bit joystick interface is probably the one you need.
https://www.leobodnar.com/shop/index.php?main_page=product_info&cPath=94&products_id=204

You might need the matrix breakout board as well, but you don't appear to need many buttons, so might not need that.

**Comment by HaunterSix** [comment]
so this board can be used for the collective axis and throttle axis?

**Comment by jdahlblom** [comment]
> You might need the matrix breakout board as well, but you don't appear to need many buttons, so might not need that.

This one? https://www.leobodnar.com/shop/index.php?main_page=product_info&products_id=274

**Comment by jdahlblom** [comment]
@HaunterSix, so with this setup there are no need to do any Arduino stuff. It is more plug 'n play.

**Comment by HaunterSix** [comment]
> @HaunterSix, so with this setup there are no need to do any Arduino stuff. It is more plug 'n play.

Awesome :D thans for the help, i am going to order bodnar boards and try this out

**Comment by No1sonuk** [comment]
> so this board can be used for the collective axis and throttle axis?

Yes.
It has 8 analogue inputs for pots or analogue Hall effect devices (I've used both on one), as well as 32+4 button inputs - the "+4" specifically show up as a hat switch, IIRC.

> > You might need the matrix breakout board as well, but you don't appear to need many buttons, so might not need that.
> 
> This one? https://www.leobodnar.com/shop/index.php?main_page=product_info&products_id=274

Yes.  The board uses a matrix for the switches.  If you're using only up to 12 buttons/switches, you don't need the matrix.
More than that requires a matrix with blocking diodes.  You can make your own, or buy the one shown.

> @HaunterSix, so with this setup there are no need to do any Arduino stuff. It is more plug 'n play.

Exactly.  The only "programming" needed would be if you want to rename it or use rotary encoders.  And that's done with the apps they provide.
