### ISSUE TITLE
[BUG] Mirage F1 EE interface json

### ISSUE THREAD

**Issue by nonobear** [DCS-Skunkworks/dcs-bios#574]
line 640
MirageF1:defineFloat("P_CE_ACCEL_U_ARROW_G", **217**, { 0, 1 }, "CE/BE/EE Accelerometer Gauges", "CE/BE/EE Pilot Accelerometer Upper Arrow")
MirageF1:defineFloat("P_CE_ACCEL_M_ARROW_G", 218, { 0, 1 }, "CE/BE/EE Accelerometer Gauges", "CE/BE/EE Pilot Accelerometer Main Arrow")
MirageF1:defineFloat("P_CE_ACCEL_L_ARROW_G", **219**, { 0, 1 }, "CE/BE/EE Accelerometer Gauges", "CE/BE/EE Pilot Accelerometer Lower Arrow")

**Comment by charliefoxtwo** [comment]
Could you please describe the issue you're experiencing?
