### ISSUE TITLE
L-39 BACK_FLAPS_*_LAMP described as "Front..."

### ISSUE THREAD

**Issue by virgo47** [DCS-Skunkworks/dcs-bios#577]
**DCS-BIOS version**
master

**Describe the bug**
Three L-39 lamps from the back cockpit are described as "Front..." which duplicates the same lamps from the front cockpit. The problem starts from this line: https://github.com/DCS-Skunkworks/dcs-bios/blob/master/Scripts/DCS-BIOS/lib/modules/aircraft_modules/L-39.lua#L221

The same in JSON: https://github.com/DCS-Skunkworks/dcs-bios/blob/master/Scripts/DCS-BIOS/doc/json/L-39.json#L10377

And also in JSONP: https://github.com/DCS-Skunkworks/dcs-bios/blob/master/Scripts/DCS-BIOS/doc/doc_assets/L-39.jsonp#L10378

I'm totally new to DCS-BIOS, I have no idea what is generated from what, so I'd rather not attempt a pull request with the fixes.

The bug manifested as duplicated actions in downstream project DCS-COINS on the Touch Portal panel.

**Comment by charliefoxtwo** [comment]
The description in the lua drives the json files (they're generated from the lua).

You're welcome to submit a PR changing the descriptions - just make sure to either run the local compile in vs code or launch a mission so that the json files are updated.

**Comment by virgo47** [comment]
I tried, compiled and created the PR. I hope there is no problem it's on master, but if so, let me know and I'll redo it on another named branch if necessary.

BTW: If I find other cosmetics problems (e.g. Huey has plenty of duplicated descriptions for various radio volumes) I can make these more specific/descriptive with the same process, right? Should I create an issue again, or is just a PR enough?

**Comment by charliefoxtwo** [comment]
Yup, this repo just runs a single master branch, so a PR into master is fine.

And yeah, no issue needed if you'd like to submit another pr for another aircraft.
