### ISSUE TITLE
[BUG] (Possible) F-16 Use address constants

### ISSUE THREAD

**Issue by Jacktherookie** [DCS-Skunkworks/dcs-bios#582]
**DCS-BIOS version**

I'm using nightly builds of DCS-BIOS Skunkworks "2024-05-19"

**DCS-BIOS Control**

Address is 0x4484
F-16C_50/LIGHT_INST_PNL

**Describe the bug**

Throws compile error while using option "Use Address Constants". Works OK with this option turned off.

**To Reproduce**

1. Copy & Paste F-16 Instrument Flood light (green) from BORT (F-16C_50/LIGHT_INST_PNL) 
DcsBios::ServoOutput lightConsles(F_16C_50_LIGHT_CONSLES_A, PIN, 544, 2400);

2. Compile or Compile & Upload!

**Expected behavior**

It should be uploaded without any errors since I'm just copy & pasting codes (that 1 line of code only)

**Screenshots**

![image](https://github.com/DCS-Skunkworks/dcs-bios/assets/39476173/366956ef-5625-4911-9b41-358b125c1d27)

**Additional context**

I'm gonna test if there is more of these problem exists in F-16. I'll update when I found more of them.
Issue #529 states solution for workaround though.

**Comment by charliefoxtwo** [comment]
Please test the solution in #529 and if that doesn't work let us know.
