### ISSUE TITLE
AH-64D - Pilot Generator Reset  Switch, GEN 1/GEN 2 - not working

### ISSUE THREAD

**Issue by AmirLavi2** [DCS-Skunkworks/dcs-bios#866]
### Version

- [X] I am using the latest version

### Aircraft

AH-64D

### Control

Generator Reset  Switch, GEN 1/GEN 2

### Description

Pilot Generator Reset  Switch, GEN 1/GEN 2 not affected in cockpit, the device id is correct. check with versions 0.81, 0.8 0.75.

AH_64D:defineSpringloaded_3PosTumb("PLT_GEN_RESET", 3, 3002, 3001, 355, "PLT Generator Panel", "Pilot Generator Reset Switch, GEN 1/GEN 2")

**Comment by charliefoxtwo** [comment]
Looks like the actual keybinds use different commands from what is defined in clickabledata.lua for some reason. Switching to those seems to work.
