### ISSUE TITLE
AH-64D: `PLT_APU_BTN_CVR` not output state + not closing

### ISSUE THREAD

**Issue by AmirLavi2** [DCS-Skunkworks/dcs-bios#878]
### Version

- [X] I am using the latest version

### Aircraft

AH-64D

### Control

Pilot APU Pushbutton Cover, OPEN/CLOSE

### Description

The APU cover not return output that he was opened + the cover not closed when toggle open/close toggle. Video example:

https://www.youtube.com/watch?v=2CKlbo104U8

**Comment by charliefoxtwo** [comment]
https://github.com/DCS-Skunkworks/dcs-bios/blob/53526f513f3ff11c4ec153d21148d0bfb600d54e/Scripts/DCS-BIOS/lib/modules/aircraft_modules/AH-64D.lua#L604

Looks like a typo - guessing the draw arg should be 401, not 4001.
