### ISSUE TITLE
Dora gunsight increments only working once

### ISSUE THREAD

**Issue by Magpieeeeeee** [DCS-Skunkworks/dcs-bios#897]
### Version

- [X] I am using the latest version

### Aircraft

FW-190D9

### Control

EZ42 Gunsight Brightness Control / EZ42 Gunsight Altitude Aiming Correction Adjusting Knob I

### Description

Dora gunsight variable steps only seem to be used for 1 click. It doesnt keep going up

### Steps to reproduce

Jump in dora
Choose variable increment for gunsight brightness
Click twice

### Expected behavior

Gunsight brightness only goes up for one increment

### Additional context

I am big noob

**Comment by charliefoxtwo** [comment]
Looks like a lot of the gunsight controls can be converted to proper axis controls - shouldn't be too difficult
