### ISSUE TITLE
Add 3 cover buttons that on the AH-64D Collective

### ISSUE THREAD

**Issue by AmirLavi2** [DCS-Skunkworks/dcs-bios#914]
### Version

- [X] I am using the latest version

### Aircraft

AH-64D

### Control

HOTAS_PLT

### Description

i added this to the code, and it works. you can add something like that :

--Collective
AH_64D:defineToggleSwitch("PLT_FLIGHT_CHOP_BTN_GUARD_CVR", 23, 3064, 558, "PLT Collective", "Pilot CHOP BTN Pushbutton Cover, OPEN/CLOSE")
AH_64D:defineToggleSwitch("PLT_FLIGHT_EMERGENCY_JETTISON_SW_GUARD_CVR", 23, 3049, 549, "PLT Collective", "Pilot EMERGENCY JETTISON Pushbutton Cover, OPEN/CLOSE")
AH_64D:defineToggleSwitch("PLT_FLIGHT_BUCS_TRIGGER_GUARD_CVR", 23, 3067, 561, "PLT Collective", "Pilot BUCS TRIGGER Pushbutton Cover, OPEN/CLOSE")

**Comment by AmirLavi2** [comment]
..with CPG:

--Collective
AH_64D:defineToggleSwitch("PLT_FLIGHT_CHOP_BTN_GUARD_CVR", 23, 3064, 558, "PLT Collective", "Pilot CHOP BTN Pushbutton Cover, OPEN/CLOSE")
AH_64D:defineToggleSwitch("CPG_FLIGHT_CHOP_BTN_GUARD_CVR", 24, 3064, 600, "CPG Collective", "Gunner CHOP BTN Pushbutton Cover, OPEN/CLOSE")
AH_64D:defineToggleSwitch("PLT_FLIGHT_EMERGENCY_JETTISON_SW_GUARD_CVR", 23, 3049, 549, "PLT Collective", "Pilot EMERGENCY JETTISON Pushbutton Cover, OPEN/CLOSE")
AH_64D:defineToggleSwitch("CPG_FLIGHT_EMERGENCY_JETTISON_SW_GUARD_CVR", 24, 3049, 591, "CPG Collective", "Gunner EMERGENCY JETTISON Pushbutton Cover, OPEN/CLOSE")
AH_64D:defineToggleSwitch("PLT_FLIGHT_BUCS_TRIGGER_GUARD_CVR", 23, 3067, 561, "PLT Collective", "Pilot BUCS TRIGGER Pushbutton Cover, OPEN/CLOSE")
AH_64D:defineToggleSwitch("CPG_FLIGHT_BUCS_TRIGGER_GUARD_CVR", 24, 3067, 603, "CPG Collective", "Gunner BUCS TRIGGER Pushbutton Cover, OPEN/CLOSE")

**Comment by charliefoxtwo** [comment]
Looks like a majority of the collective controls should be addable. The cyclic controls appear unlikely though (I know that wasn't mentioned in the feature request, just figured I'd document).
