### ISSUE TITLE
AH-64D: CPG Internal light panel adresses mix

### ISSUE THREAD

**Issue by AmirLavi2** [DCS-Skunkworks/dcs-bios#922]
### Version

- [X] I am using the latest version

### Aircraft

AH-64D

### Control

Light_Panel

### Description

Mixed address in the cpg inernal lights panel.
For example Primary press the light test

**Comment by charliefoxtwo** [comment]
@AmirLavi2 could you provide more details as to what you're seeing and what you expect? I'm not clear what the problem is from the description provided.

**Comment by AmirLavi2** [comment]
All the function in the cpg light panel is not work 
It islook like the address of the knob are look like wrong
And the pushbutton test light notwork
